# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ec1c412269bb673a0338c8ef82d85af47e4cc3b176da2a820f1234977079c010d73e18e296cb8a57598d0268c7b2a36e16e77c53582758ad4ef600136110ee0d

test:
  secret_key_base: 7946655cf5e587852e1abe95bd4449cefc97ed1e82cf530393ff294df3c05a3916a843793e323f713ca65aa508b3fda89f1002798349122dc1c6e022f9b2d03e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
